noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = false
[[build.cachebusters]]
    source = 'assets/.*\.(js|ts|jsx|tsx)'
    target = 'js'
[[build.cachebusters]]
    source = 'assets/.*\.scss'
    target = 'css'
    